---
title: "Suivi"
output: md_document
---

## Semaine 1 : Lundi 1er Mars 2021 au Dimanche 7 Mars 2021

### Objectif(s) de la semaine :

- Trouver des articles parlant de méthodes de noyaux consensus.
- Trouver des librairies où ces méthodes ont été implémentées.

### Récapitulatif des choses faites :

- Sélection d'articles en lien avec les noyaux consensus.
- Construction d'une base de référence pour les méthodes en lien avec le noyaux consensus.
- Premières lectures des articles liés aux méthodes.

### Question(s) :

1. Est ce que le terme "noyaux consensus" est uniquement un terme pour définir un mélange de noyaux, ou est-il plus spécifique ?
2. Quels sont les mesures que nous pouvons appliqués entre des variables qualitatives afin de quantifier une similarité ?



## Semaine 2 : Lundi 8 Mars 2021 au Dimanche 14 Mars 2021

### Réponses aux questions de la semaine précédente :

1.
2.

### Objectif(s) de la semaine :

- Comprendre le coeur des méthodes "principales/efficaces".
- Approfondissement des lectures des articles sélectionnés.
- Trouver des librairies où les méthodes ont été implémentées.

### Récapitulatif des choses faites :


### Question(s) :

