---
title: "Exemple SCMK"
---
# Chargement des librairies et des fonctions

## Chargement des library
```{r}
rm(list=ls())
library(orthoDr)
library(pracma)
library(quadprog)
library(aricode) 
library(fossil)
library(ggplot2)
library(tidyverse)
```

## Clustering

```{r}
fun<-function(P,args){
  res = args$beta * Trace(t(P) %*% args$L %*% P) + args$gamma * base::norm(args$F1 - P %*% args$Q,type='F')^2
  return(res)
}

grad<-function(P,args){
  res = 2*args$beta * args$L %*% P - 2 * args$gamma * args$F1 %*% t(args$Q) 
  return(res)
}
```

```{r}
SCMK <- function(Kernel,c=3,alpha=1,beta=1,gamma=1,mu=1,nb_etape=200,tol=1e-3){
  #Kernel : tensor with dim(n,n,r) where Kernel[:,:,k] is the kernel k on Kernel
  # c : number of cluster 
  
  
  # Initialisation des variables 
  if(length(dim(Kernel))==2){
    r = 1
    n = dim(Kernel)[1]
  }
  else {
    r = dim(Kernel)[3]
    n = dim(Kernel)[1]
  }
  Z = matrix(runif(n*n,0,1),nrow=n,ncol=n)
  P = gramSchmidt( matrix(runif(n*c,0,1),nrow=n,ncol=c))$Q
  Q = gramSchmidt( matrix(runif(c*c,0,1),nrow=c,ncol=c))$Q
  F1 = P %*% Q
  
  list_argmax=max.col(F1)#donne liste indice du max par ligne
  for (i in 1:n){
    F1[i,list_argmax[i]] = 1
    F1[i,-list_argmax[i]] = 0
  }
  F_init=F1
  Y = matrix(0,nrow=n,ncol=n) 
  w = matrix(1,nrow=r,ncol=1)/(r^2) ## On veut que sum(sqrt(w))=1
  
  etape=1
  
  
  S = matrix(0,nrow=n,ncol=n)
  h = matrix(1,nrow=r,ncol=1)
  
  while( (etape<nb_etape+1) & (base::norm(Z-S,type='F') > base::norm(Z,type='F')*tol) ){
    #print(etape)
    #''' Calcul de Kw '''
    Kw = matrix(0,nrow=n,ncol=n)
    
    if(r==1) {
      Kw = Kernel
    }
    else {
      for (i in 1:r) Kw = Kw + w[i]*Kernel[,,i]
    }
    
    #  Update de S 
    S = Z-Y/mu
    S[abs(S)<alpha/mu] = alpha/mu
    S = (abs(S)-alpha/mu) * sign(S)
    S = S-diag(diag(S))
    S[S<0]=0
    
    # Update de Z 
    E = S + Y/mu
    dist_p = (P^2) %*% matrix(1,nrow=c,ncol=n) - 2 * P %*% t(P) + matrix(1,nrow=n,ncol=c) %*% t(P^2) # ||P_i,: - P_j,:||^2
    tmp1 = mu*diag(n) + 2*Kw
    tmp2 = beta/2 * dist_p - 2* Kw - mu * E # voir si c'est E ou t(E) matlab
    Z = solve(tmp1) %*% (-tmp2)
    Z = Z - diag(diag(Z))
    Z[Z<0] = 0
    Z = (Z+t(Z))/2
    
    # Update de Y 
    Y = Y + mu * (S-Z)
    
    #  Update de P 
    D = diag(rowSums(Z))
    L = D - Z
    args=list('L'=L,'F1'=F1,'Q'=Q,'beta'=beta,'gamma'=gamma)
    P = ortho_optim(P,fun,grad=grad,args= args,verbose = FALSE)$B
    
    # Update de Q 
    decomposition = svd(t(F1) %*% P)
    Q = decomposition$u %*% t(decomposition$v)
    
    #  Update de F 
    F1 = P %*% Q
    list_argmax=max.col(F1) #donne liste indice du max par ligne
    for (i in 1:n){
      F1[i,list_argmax[i]] = 1
      F1[i,-list_argmax[i]] = 0
    }
    if(r>1){
      #''' Calcul de h '''
      for (i in 1:r) h[i] = Trace( Kernel[,,i] - 2*Kernel[,,i]%*%Z + t(Z) %*% Kernel[,,i] %*%Z )
      
      #''' Update de w '''
      w = (h * sum(1./h))^(-2)
    }
    etape=etape+1
    #print(dist_p)
  }
  #print(Z)
  #print(S)
  output=list("pred"=list_argmax,"Z"=Z,'K'=Kw,'w'=w,'P'=P,'F'=F1,'F_init'=F_init)
  return(output)
}
```

```{r}
Self_expressiveness <- function(Kernel,alpha=1,mu=1,nb_etape=200,tol=1e-3){
  #Kernel : tensor with dim(n,n,r) where Kernel[:,:,k] is the kernel k on Kernel
  
  
  # Initialisation des variables 
  if(length(dim(Kernel))==2){
    r = 1
    n = dim(Kernel)[1]
  }
  else {
    r = dim(Kernel)[3]
    n = dim(Kernel)[1]
  }
  Z = matrix(runif(n*n,0,1),nrow=n,ncol=n)
  
  Y = matrix(0,nrow=n,ncol=n)
  w = matrix(1,nrow=r,ncol=1)/(r^2) ## On veut que sum(sqrt(w))=1
  
  etape=1
  
  
  S = matrix(0,nrow=n,ncol=n)
  h = matrix(1,nrow=r,ncol=1)
  
  while( (etape<nb_etape+1) & (base::norm(Z-S,type='F') > base::norm(Z,type='F')*tol) ){
    #''' Calcul de Kw '''
    Kw = matrix(0,nrow=n,ncol=n)
    
    if(r==1) {
      Kw = Kernel
    }
    else {
      for (i in 1:r) Kw = Kw + w[i]*Kernel[,,i]
    }
    
    #  Update de S 
    S = Z-Y/mu
    S[abs(S)<alpha/mu] = alpha/mu
    S = (abs(S)-alpha/mu) * sign(S)
    S = S-diag(diag(S))
    S[S<0]=0
    
    # Update de Z 
    E = S + Y/mu
    tmp1 = mu*diag(n) + 2*Kw
    tmp2 = - 2* Kw - mu * E
    Z = solve(tmp1) %*% (-tmp2)
    
    Z = Z - diag(diag(Z))
    Z[Z<0] = 0
    Z = (Z+t(Z))/2
    
    # Update de Y 
    Y = Y + mu * (S-Z)
    
    if(r>1){
      #''' Calcul de h '''
      for (i in 1:r) h[i] = Trace( Kernel[,,i] - 2*Kernel[,,i]%*%Z + t(Z) %*% Kernel[,,i] %*%Z )
      
      #''' Update de w '''
      w = (h * sum(1./h))^(-2)
    }
    etape=etape+1
  }
  output=list("Z"=Z,'K'=Kw,'w'=w)
  return(output)
}

specc_adjacence<-function(X, c){
  n=nrow(X)
  L = diag(rowSums(X)) - X
  P = svd(L)
  P = P$u[,(n-c+1):n]
  for (i in 1:nrow(P))
  {
    P[i,]=P[i,]/sqrt(sum(P[i,]^2))
  }
  res=kmeans(P,3,nstart=30)
  return(res$cluster)
}
```

```{r}
SCMK_KMEANS <- function(Kernel,c=3,alpha=1,beta=1,mu=1,nb_etape=200,tol=1e-3){
  #Kernel : tensor with dim(n,n,r) where Kernel[:,:,k] is the kernel k on Kernel
  # c : number of cluster 
  
  
  # Initialisation des variables 
  if(length(dim(Kernel))==2){
    r = 1
    n = dim(Kernel)[1]
  }
  else {
    r = dim(Kernel)[3]
    n = dim(Kernel)[1]
  }
  Z = matrix(runif(n*n,0,1),nrow=n,ncol=n)
  P = gramSchmidt( matrix(runif(n*c,0,1),nrow=n,ncol=c))$Q
  
  F1 = zeros(n,c)
  res=kmeans(P,c)$cluster
  for (i in 1:n){
    F1[i,res[i]] = 1
  }
  
  Y = matrix(0,nrow=n,ncol=n)
  w = matrix(1,nrow=r,ncol=1)/(r^2) ## On veut que sum(sqrt(w))=1
  
  etape=1
  
  
  S = matrix(0,nrow=n,ncol=n)
  h = matrix(1,nrow=r,ncol=1)
  
  while( (etape<nb_etape+1) & (base::norm(Z-S,type='F') > base::norm(Z,type='F')*tol) ){
    #print(etape)
    #''' Calcul de Kw '''
    Kw = matrix(0,nrow=n,ncol=n)
    
    if(r==1) {
      Kw = Kernel
    }
    else {
      for (i in 1:r) Kw = Kw + w[i]*Kernel[,,i]
    }
    
    #  Update de S 
    S = Z-Y/mu
    S[abs(S)<alpha/mu] = alpha/mu
    S = (abs(S)-alpha/mu) * sign(S)
    S = S-diag(diag(S))
    S[S<0]=0
    
    # Update de Z 
    E = S + Y/mu
    dist_p = (P^2) %*% matrix(1,nrow=c,ncol=n) - 2 * P %*% t(P) + matrix(1,nrow=n,ncol=c) %*% t(P^2) # ||P_i,: - P_j,:||^2
    tmp1 = mu*diag(n) + 2*Kw
    tmp2 = beta/2 * dist_p - 2* Kw - mu * E
    Z = solve(tmp1) %*% (-tmp2)
    Z = Z - diag(diag(Z))
    Z[Z<0] = 0
    Z = (Z+t(Z))/2
    
    # Update de Y 
    Y = Y + mu * (S-Z)
    
    #  Update de P 
    D = diag(rowSums(Z))
    L = D - Z
    P = svd(L)
    P = P$u[,(n-c+1):n]
    for (i in 1:nrow(P))
    {
      P[i,]=P[i,]/sqrt(sum(P[i,]^2))
    }
    #  Update de F 
    res=kmeans(P,c,nstart = 30)$cluster
    for (i in 1:n){
      F1[i,res[i]] = 1
      F1[i,-res[i]] = 0
    }
    if(r>1){
      #''' Calcul de h '''
      for (i in 1:r) h[i] = Trace( Kernel[,,i] - 2*Kernel[,,i]%*%Z + t(Z) %*% Kernel[,,i] %*%Z )
      
      #''' Update de w '''
      w = (h * sum(1./h))^(-2)
    }
    etape=etape+1
  }
  output=list("pred"=res,"Z"=Z,'K'=Kw,'w'=w,'P'=P,'F'=F1)
  return(output)
}
```

```{r}
RBF<-function(X,sigma=1){
  n=nrow(X)
  res=matrix(0,n,n)
  for(i in 1:n){
    for(j in 1:n){
      res[i,j]=exp(-sum((X[i,]-X[j,])^2)/(2*sigma))
    }
  }
  return(res)
}

polynomial<-function(X,deg=1){
  n=nrow(X)
  res=matrix(0,n,n)
  for(i in 1:n){
    for(j in 1:n){
      res[i,j]=(t(X[i,])%*%X[j,]+1)^deg
    }
  }
  return(res)
}
```


## Optimisation hyper-paramètres :

```{r}
score_grille_hyperparametre_SCMK<-function(Kernel, Y, c=3, range=3, mu=1e3,nb_etape=50,nb_run=1){
  N_range = 2 * range + 1
  list_res_NMI <- c()
  list_res_ARI <- c()
  Mat_res_NMI = zeros(N_range,N_range)
  Mat_res_ARI = zeros(N_range,N_range)
  
  tmp_res_NMI = rep(0,nb_run)
  tmp_res_ARI = rep(0,nb_run)
  for (a in -range:range){
    for (b in -range:range){
      for(g in -range:range){
        print(c(a,b,g))
        for(x in 1:nb_run){
          res=SCMK(Kernel = Kernel,c=c,nb_etape=nb_etape,mu=mu,gamma =10^g,alpha=10^a,beta=10^b)
          tmp_res_NMI[x] = NMI(as.vector(Y),as.vector(res$pred))
          tmp_res_ARI[x] = adj.rand.index(Y,res$pred)
        }
        Mat_res_NMI[b+(range+1),g+(range+1)] = mean(tmp_res_NMI)
        Mat_res_ARI[b+(range+1),g+(range+1)] = mean(tmp_res_ARI)
      }
    }
    list_res_NMI[[a+(range+1)]]=Mat_res_NMI
    list_res_ARI[[a+(range+1)]]=Mat_res_ARI
  }
  output = list("score_NMI" = list_res_NMI, "score_ARI" = list_res_ARI)
  return(output)
}

setup_hyperparametre_SCMK <- function(liste, range){
  N_range=2 * range + 1
  tmp_res <- c()
  tmp_index <-c()
  b <- c()
  g <- c()
  for (a in 1:N_range){
    tmp_res[a] = max(liste[[a]])
    tmp_index[a] = which.max(liste[[a]])
    if(tmp_index[[a]] %% N_range != 0){
      b[a] = tmp_index[[a]] %% N_range # Reste division entière 
      g[a] = tmp_index[[a]] %/% N_range +1 # Partie entière division
    }
    else{
      b[a] = N_range
      g[a] = tmp_index[[a]] %/% N_range
    }
  }
  a = which.max(tmp_res)
  output = list("alpha"=10^(a-(range+1)),"beta"= 10^(b[a]-(range+1)),"gamma" = 10^(g[a]-(range+1)),"score_max" = max(tmp_res))
  return(output)
}
```



```{r}
score_grille_hyperparametre_SCMK_KMEANS<-function(Kernel, Y, c=3, range=3, mu=1e3,nb_etape=50,nb_run=1){
  N_range = 2 * range + 1
  Mat_res_NMI = zeros(N_range,N_range)
  Mat_res_ARI = zeros(N_range,N_range)
  
  tmp_res_NMI = rep(0,nb_run)
  tmp_res_ARI = rep(0,nb_run)
  for (a in -range:range){
    for (b in -range:range){
      print(c(a,b))
      for(x in 1:nb_run){
        res=SCMK_KMEANS(Kernel = Kernel,c=c,nb_etape=nb_etape,mu=mu,alpha=10^a,beta=10^b)
        tmp_res_NMI[x] = NMI(as.vector(Y),as.vector(res$pred))
        tmp_res_ARI[x] =adj.rand.index(Y,res$pred)
      }
      Mat_res_NMI[a+(range+1),b+(range+1)] = mean(tmp_res_NMI)
      Mat_res_ARI[a+(range+1),b+(range+1)] = mean(tmp_res_ARI)
    }
  }
  output = list("score_NMI" = Mat_res_NMI, "score_ARI" = Mat_res_ARI)
  return(output)
}

setup_hyperparametre_SCMK_KMEANS <- function(liste, range){
  N_range=2 * range + 1
  tmp_res = max(liste)
  tmp_index = which.max(liste)
  if(tmp_index %% N_range != 0){
    a = tmp_index %% N_range # Reste division entière 
    b = tmp_index %/% N_range +1 # Partie entière division
  }
  else{
    a = N_range
    b = tmp_index %/% N_range
  }
  output = list("alpha"=10^(a-(range+1)),"beta"= 10^(b-(range+1)),"score_max" = tmp_res)
  return(output)
}
```


```{r}
hyperparametre_Self_expressiveness<-function(Kernel, Y, c=3, range=3, mu=1e3,nb_etape=50,nb_run=1){
  N_range = 2 * range + 1
  Mat_res_NMI = zeros(N_range,1)
  Mat_res_ARI = zeros(N_range,1)
  tmp_res_NMI = rep(0,nb_run)
  tmp_res_ARI = rep(0,nb_run)
  for (a in -range:range){
    print(a)
    for(x in 1:nb_run){
      affinity_self=Self_expressiveness(Kernel = Kernel,nb_etape=nb_etape,mu=mu,alpha=10^a)
      res=specc_adjacence(affinity_self$Z,c = c)
      tmp_res_NMI[x] = NMI(as.vector(Y),as.vector(res))
      tmp_res_ARI[x] =adj.rand.index(Y,res)
    }
    Mat_res_NMI[a+(range+1)] = mean(tmp_res_NMI)
    Mat_res_ARI[a+(range+1)] = mean(tmp_res_ARI)
  }
  a_NMI=which.max(Mat_res_NMI)
  a_ARI=which.max(Mat_res_ARI)
  output = list("alpha_NMI"=10^(a_NMI-(range+1)),"alpha_ARI"=10^(a_ARI-(range+1)), "score_max_NMI" = max(Mat_res_NMI) ,"score_max_ARI" = max(Mat_res_ARI) ,"score_NMI" = Mat_res_NMI, "score_ARI" = Mat_res_ARI)
  return(output)
}
```


# Exemple : 3 gaussiennes - Single Kernel
## Génération des données 

```{r}
N_train = 100
X1=matrix(rnorm(2*N_train),nrow=N_train,ncol=2)
X2=matrix(rnorm(2*N_train,3),nrow=N_train,ncol=2)
X3=matrix(rnorm(2*N_train,6),nrow=N_train,ncol=2)
X_train=as.matrix(rbind(X1,X2,X3))
Y_train = c(rep(1,N_train),rep(2,N_train),rep(3,N_train))
```

```{r}
N_test = 50
X1=matrix(rnorm(2*N_test),nrow=N_test,ncol=2)
X2=matrix(rnorm(2*N_test,3),nrow=N_test,ncol=2)
X3=matrix(rnorm(2*N_test,6),nrow=N_test,ncol=2)
X_test=as.matrix(rbind(X1,X2,X3))
Y_test = c(rep(1,N_test),rep(2,N_test),rep(3,N_test))
```

```{r}
for (p in 1:ncol(X_train)){
  X_train[,p] =  (X_train[,p] - mean( X_train[,p]))/sd( X_train[,p])
  X_test[,p] =  (X_test[,p] - mean( X_test[,p]))/sd( X_test[,p])
}
```

## Visualisation des données

```{r}
setwd("SCMK - image")

ggplot(data.frame(cbind(X_train,Y_train))) +  aes(x=V1,y=V2,col=as.factor(Y_train)) + geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")
ggsave('Plot_gaussian_train.png')

ggplot(data.frame(cbind(X_test,Y_test))) +  aes(x=V1,y=V2,col=as.factor(Y_test)) + geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")
ggsave('Plot_gaussian_test.png')


ggplot(data.frame(cbind(rbind(X_train,X_test),c(Y_train,Y_test),rep(c("Train","Test"),times=c(3*N_train,3*N_test))))) +  aes(x=as.numeric(X1),y=as.numeric(X2),col=as.factor(X3),shape=as.factor(X4)) + geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe",shape="Data")
ggsave('Plot_gaussian_train_and_test.png')
```


## Construction du Kernel

```{r}
setwd("SCMK - image")
Kernel_Matrix_train=RBF(X_train,1)

Kernel_Matrix_train %>% # Data wrangling
  as_tibble() %>%
  rowid_to_column(var="X") %>%
  gather(key="Y", value="Z", -1) %>%
  
  # Change Y to numeric
  mutate(Y=as.numeric(gsub("V","",Y))) %>%
  
  # Viz
  ggplot(aes(X, Y, fill= Z)) + 
  geom_tile()+
  theme(legend.position="none")
ggsave('Kernel_RBF_1_train.png')
```


```{r}
setwd("SCMK - image")
Kernel_Matrix_test = RBF(X_test,1)

Kernel_Matrix_test %>% # Data wrangling
  as_tibble() %>%
  rowid_to_column(var="X") %>%
  gather(key="Y", value="Z", -1) %>%
  
  # Change Y to numeric
  mutate(Y=as.numeric(gsub("V","",Y))) %>%
  
  # Viz
  ggplot(aes(X, Y, fill= Z)) + 
  geom_tile()+
  theme(legend.position="none")
ggsave('Kernel_RBF_1_test.png')
```

## Test des performances

```{r}
range = 3

c=3
nb_etape = 50
nb_run = 5
nb_test = 30

result_NMI_test<-matrix(0,nrow=nb_test,ncol = 3)
result_ARI_test<-matrix(0,nrow=nb_test,ncol = 3)

#exp_mu = 1
```


```{r}
for( exp_mu in -range:range){
  mu=10 ^exp_mu  
  # Setup des hyper-paramètres
  tmp=score_grille_hyperparametre_SCMK(Kernel_Matrix_train, Y_train, c,range,mu,nb_etape = nb_etape ,nb_run = nb_run)
  param_SCMK_ARI=setup_hyperparametre_SCMK(tmp$score_ARI,range)
  param_SCMK_NMI=setup_hyperparametre_SCMK(tmp$score_NMI,range)
  
  tmp=score_grille_hyperparametre_SCMK_KMEANS(Kernel_Matrix_train, Y_train,c,range,mu,nb_etape = nb_etape ,nb_run = nb_run)
  param_SCMK_KMEANS_ARI = setup_hyperparametre_SCMK_KMEANS(tmp$score_ARI,range)
  param_SCMK_KMEANS_NMI = setup_hyperparametre_SCMK_KMEANS(tmp$score_NMI,range)
  
  param_Self=hyperparametre_Self_expressiveness(Kernel_Matrix_train, Y_train, c,range,mu,nb_etape = nb_etape ,nb_run = nb_run)
  
  
  #######  
  # Visualisation prediction sur le train :
  setwd("/SCMK - image/Single Kernel/Train")
  #SCMK_NMI
  res=SCMK(Kernel = Kernel_Matrix_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_NMI$alpha, beta=param_SCMK_NMI$beta, gamma=param_SCMK_NMI$gamma)
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe") + 
    ggtitle(paste("NMI : ", round(NMI(as.vector(Y_train),as.vector(res$pred)),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_NMI_Mu_1e',exp_mu,".png",sep = ""))
  
  #SCMK_ARI
  
  res=SCMK(Kernel = Kernel_Matrix_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_ARI$alpha, beta=param_SCMK_ARI$beta, gamma=param_SCMK_ARI$gamma)
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("ARI : ", round(adj.rand.index(Y_train,res$pred),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_ARI_Mu_1e',exp_mu,".png",sep = ""))
  
  #SCMK_KMEANS_NMI
  res=SCMK_KMEANS(Kernel = Kernel_Matrix_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_NMI$alpha, beta=param_SCMK_KMEANS_NMI$beta)
  
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("NMI : ", round(NMI(as.vector(Y_train),as.vector(res$pred)),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_KMEANS_MNI_Mu_1e',exp_mu,".png",sep = "")) 
  
  
  #SCMK_KMEANS_ARI
  res=SCMK_KMEANS(Kernel = Kernel_Matrix_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_ARI$alpha, beta=param_SCMK_KMEANS_ARI$beta)
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("ARI : ", round(adj.rand.index(Y_train,res$pred),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_KMEANS_ARI_Mu_1e',exp_mu,".png",sep = ""))
  
  #Self_expressiveness_NMI
  affinity_self = Self_expressiveness(Kernel = Kernel_Matrix_train, alpha = param_Self$alpha_NMI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
  res = specc_adjacence(affinity_self$Z,c = c)
  
  ggplot(data.frame(cbind(X_train,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
    xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("NMI : ", round(NMI(as.vector(Y_train),as.vector(res)),4) ,sep = ""))
  ggsave(paste('Predi_SELF_EXP_MNI_Mu_1e',exp_mu,".png",sep = ""))
  
  #Self_expressiveness_ARI
  affinity_self = Self_expressiveness(Kernel = Kernel_Matrix_train, alpha = param_Self$alpha_ARI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
  res = specc_adjacence(affinity_self$Z,c = c)
  
  ggplot(data.frame(cbind(X_train,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
    xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("ARI : ", round(adj.rand.index(Y_train,res),4) ,sep = ""))
  ggsave(paste('Predi_SELF_EXP_ARI_Mu_1e',exp_mu,".png",sep = ""))
  
  
  #######  
  # Scoring
  setwd("/SCMK - image/Single Kernel/Test")
  for (i in 1:nb_test){
    print(i)
    
    #SCMK_NMI
    res=SCMK(Kernel = Kernel_Matrix_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_NMI$alpha, beta=param_SCMK_NMI$beta, gamma=param_SCMK_NMI$gamma)
    result_NMI_test[i,1] <- NMI(as.vector(Y_test),as.vector(res$pred))
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe") + 
        ggtitle(paste("NMI : ", round(result_NMI_test[i,1],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_NMI_Mu_1e',exp_mu,".png",sep = ""))
    }
    
    #SCMK_ARI
    
    res=SCMK(Kernel = Kernel_Matrix_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_ARI$alpha, beta=param_SCMK_ARI$beta, gamma=param_SCMK_ARI$gamma)
    result_ARI_test[i,1] <-adj.rand.index(Y_test,res$pred)
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("ARI : ", round(result_ARI_test[i,1],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_ARI_Mu_1e',exp_mu,".png",sep = ""))
    }
    
    #SCMK_KMEANS_NMI
    res=SCMK_KMEANS(Kernel = Kernel_Matrix_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_NMI$alpha, beta=param_SCMK_KMEANS_NMI$beta)
    result_NMI_test[i,2] <- NMI(as.vector(Y_test),as.vector(res$pred))
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("NMI : ", round(result_NMI_test[i,2],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_KMEANS_MNI_Mu_1e',exp_mu,".png",sep = "")) 
    }
    
    #SCMK_KMEANS_ARI
    res=SCMK_KMEANS(Kernel = Kernel_Matrix_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_ARI$alpha, beta=param_SCMK_KMEANS_ARI$beta)
    result_ARI_test[i,2] <-adj.rand.index(Y_test,res$pred)
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("ARI : ", round(result_ARI_test[i,2],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_KMEANS_ARI_Mu_1e',exp_mu,".png",sep = ""))
    }
    
    #Self_expressiveness_NMI
    affinity_self = Self_expressiveness(Kernel = Kernel_Matrix_test, alpha = param_Self$alpha_NMI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
    res = specc_adjacence(affinity_self$Z,c = c)
    result_NMI_test[i,3] <- NMI(as.vector(Y_test),as.vector(res))
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
        xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("NMI : ", round(result_NMI_test[i,3],4) ,sep = ""))
      ggsave(paste('Predi_SELF_EXP_MNI_Mu_1e',exp_mu,".png",sep = ""))
    }
    
    #Self_expressiveness_ARI
    affinity_self = Self_expressiveness(Kernel = Kernel_Matrix_test, alpha = param_Self$alpha_ARI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
    res = specc_adjacence(affinity_self$Z,c = c)
    result_ARI_test[i,3] <-adj.rand.index(Y_test,res)
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
        xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("ARI : ", round(result_ARI_test[i,3],4) ,sep = ""))
      ggsave(paste('Predi_SELF_EXP_ARI_Mu_1e',exp_mu,".png",sep = ""))
    }
    
    
  }  
  
  #######
  # Boxplot
  name_file_NMI=paste("Boxplot_NMI_Mu_1e",exp_mu,".png",sep = "")
  df_result_NMI = data.frame(cbind(matrix(result_NMI_test,nrow=3*nb_test),rep(c("SCMK","SCMK_KMEANS","SELF_EXP"),each=nb_test)))
  colnames(df_result_NMI) <- c("NMI","Methode")
  df_result_NMI$NMI <- as.numeric(df_result_NMI$NMI)
  ggplot(df_result_NMI,aes(x=Methode,y=NMI,fill=Methode)) + geom_boxplot() + ylim(0,1)
  ggsave(name_file_NMI)
  
  
  name_file_ARI=paste("Boxplot_ARI_Mu_1e",exp_mu,".png",sep = "")
  df_result_ARI = data.frame(cbind(matrix(result_ARI_test,nrow=3*nb_test),rep(c("SCMK","SCMK_KMEANS","SELF_EXP"),each=nb_test)))
  colnames(df_result_ARI) <- c("ARI","Methode")
  df_result_ARI$ARI <- as.numeric(df_result_ARI$ARI)
  ggplot(df_result_ARI,aes(x=Methode,y=ARI,fill=Methode)) + geom_boxplot() + ylim(0,1) 
  ggsave(name_file_ARI)
  
}
```


# Exemple : 3 gaussiennes - Multiple Kernels

```{r}
library(tensorr)
```

```{r}
dims_train=c(N_train*3,N_train*3,5)
Kernels_train = array(0,dims_train)
Kernels_train[,,1] = RBF(X_train,0.1)
Kernels_train[,,2] = RBF(X_train,1)
Kernels_train[,,3] = RBF(X_train,10)
Kernels_train[,,4] = polynomial(X_train,1)
Kernels_train[,,5] = polynomial(X_train,2)

res=Self_expressiveness(Kernel = Kernels_train,alpha = 10^3,mu=10^-2,nb_etape = 50,tol = 1e-3)


plot(X_train[,1],X_train[,2],col=specc_adjacence(res$Z,c = 3))
plot(X_train[,1],X_train[,2],col=specc_adjacence(res$K,c = 3))
```


```{r}
setwd("SCMK - image")
res$Z %>% # Data wrangling
  as_tibble() %>%
  rowid_to_column(var="X") %>%
  gather(key="Y", value="Z", -1) %>%
  
  # Change Y to numeric
  mutate(Y=as.numeric(gsub("V","",Y))) %>%
  
  # Viz
  ggplot(aes(X, Y, fill= Z)) + 
  geom_tile()+
  theme(legend.position="none")
ggsave('MultiKernels_Affinity_Matrix_SelfExp_train.png')

res$K %>% # Data wrangling
  as_tibble() %>%
  rowid_to_column(var="X") %>%
  gather(key="Y", value="Z", -1) %>%
  
  # Change Y to numeric
  mutate(Y=as.numeric(gsub("V","",Y))) %>%
  
  # Viz
  ggplot(aes(X, Y, fill= Z)) + 
  geom_tile()+
  theme(legend.position="none")
ggsave('MultiKernels_MixKernels_SelfExp_train.png')
```



```{r}
dims_test=c(N_test*3,N_test*3,5)
Kernels_test = array(0,dims_test)
Kernels_test[,,1] = RBF(X_test,0.1)
Kernels_test[,,2] = RBF(X_test,1)
Kernels_test[,,3] = RBF(X_test,10)
Kernels_test[,,4] = polynomial(X_test,1)
Kernels_test[,,5] = polynomial(X_test,2)

res=Self_expressiveness(Kernel = Kernels_test,alpha = 10^3,mu=10^-2,nb_etape = 50,tol = 1e-3)
plot(X_test[,1],X_test[,2],col=specc_adjacence(res$Z,c = 3))
plot(X_test[,1],X_test[,2],col=specc_adjacence(res$K,c = 3))
```

```{r}
setwd("SCMK - image")
res$Z %>% # Data wrangling
  as_tibble() %>%
  rowid_to_column(var="X") %>%
  gather(key="Y", value="Z", -1) %>%
  
  # Change Y to numeric
  mutate(Y=as.numeric(gsub("V","",Y))) %>%
  
  # Viz
  ggplot(aes(X, Y, fill= Z)) + 
  geom_tile()+
  theme(legend.position="none")
ggsave('MultiKernels_Affinity_Matrix_SelfExp_test.png')


res$K %>% # Data wrangling
  as_tibble() %>%
  rowid_to_column(var="X") %>%
  gather(key="Y", value="Z", -1) %>%
  
  # Change Y to numeric
  mutate(Y=as.numeric(gsub("V","",Y))) %>%
  
  # Viz
  ggplot(aes(X, Y, fill= Z)) + 
  geom_tile()+
  theme(legend.position="none")
ggsave('MultiKernels_MixKernels_SelfExp_test.png')
```


```{r}
range = 3
c=3
nb_etape = 50
nb_run = 5
nb_test = 30


result_NMI_test<-matrix(0,nrow=nb_test,ncol = 3)
result_ARI_test<-matrix(0,nrow=nb_test,ncol = 3)
#exp_mu=3

kernel_names <- c("RBF01","RBF1","RBF10","Poly1","Poly2")
methodes <- c("SCMK","SCMK_KMEANS","SELF_EXP")
nb_methode = length(methodes)
nb_kernels = length(kernel_names)

poids_ARI = matrix(0,nrow=nb_kernels, ncol=nb_methode)
poids_NMI = matrix(0,nrow=nb_kernels, ncol=nb_methode)
```

```{r}
for( exp_mu in -range:range){
  mu=10 ^exp_mu  
  # Setup des hyper-paramètres
  tmp=score_grille_hyperparametre_SCMK(Kernels_train, Y_train, c,range,mu,nb_etape = nb_etape ,nb_run = nb_run)
  param_SCMK_ARI=setup_hyperparametre_SCMK(tmp$score_ARI,range)
  param_SCMK_NMI=setup_hyperparametre_SCMK(tmp$score_NMI,range)
  
  tmp=score_grille_hyperparametre_SCMK_KMEANS(Kernels_train, Y_train,c,range,mu,nb_etape = nb_etape ,nb_run = nb_run)
  param_SCMK_KMEANS_ARI = setup_hyperparametre_SCMK_KMEANS(tmp$score_ARI,range)
  param_SCMK_KMEANS_NMI = setup_hyperparametre_SCMK_KMEANS(tmp$score_NMI,range)
  
  param_Self=hyperparametre_Self_expressiveness(Kernels_train, Y_train, c,range,mu,nb_etape = nb_etape ,nb_run = nb_run)
  
  #######
  # Visualisation prediction sur le train :
  
  
  setwd("/SCMK - image/MultiKernels/Train")
  #SCMK_NMI
  res=SCMK(Kernel = Kernels_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_NMI$alpha, beta=param_SCMK_NMI$beta, gamma=param_SCMK_NMI$gamma)
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe") + 
    ggtitle(paste("NMI : ", round(NMI(as.vector(Y_train),as.vector(res$pred)),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_NMI_Mu_1e',exp_mu,".png",sep = ""))
  
  #SCMK_ARI
  
  res=SCMK(Kernel = Kernels_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_ARI$alpha, beta=param_SCMK_ARI$beta, gamma=param_SCMK_ARI$gamma)
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("ARI : ", round(adj.rand.index(Y_train,res$pred),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_ARI_Mu_1e',exp_mu,".png",sep = ""))
  
  #SCMK_KMEANS_NMI
  res=SCMK_KMEANS(Kernel = Kernels_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_NMI$alpha, beta=param_SCMK_KMEANS_NMI$beta)
  
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("NMI : ", round(NMI(as.vector(Y_train),as.vector(res$pred)),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_KMEANS_MNI_Mu_1e',exp_mu,".png",sep = "")) 
  
  #SCMK_KMEANS_ARI
  res=SCMK_KMEANS(Kernel = Kernels_train, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_ARI$alpha, beta=param_SCMK_KMEANS_ARI$beta)
  ggplot(data.frame(cbind(X_train,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
    geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("ARI : ", round(adj.rand.index(Y_train,res$pred),4) ,sep = ""))
  ggsave(paste('Predi_SCMK_KMEANS_ARI_Mu_1e',exp_mu,".png",sep = ""))
  
  #Self_expressiveness_NMI
  affinity_self = Self_expressiveness(Kernel = Kernels_train, alpha = param_Self$alpha_NMI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
  res = specc_adjacence(affinity_self$Z,c = c)
  
  ggplot(data.frame(cbind(X_train,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
    xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("NMI : ", round(NMI(as.vector(Y_train),as.vector(res)),4) ,sep = ""))
  ggsave(paste('Predi_SELF_EXP_MNI_Mu_1e',exp_mu,".png",sep = ""))
  
  #Self_expressiveness_ARI
  affinity_self = Self_expressiveness(Kernel = Kernels_train, alpha = param_Self$alpha_ARI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
  res = specc_adjacence(affinity_self$Z,c = c)
  
  ggplot(data.frame(cbind(X_train,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
    xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
    ggtitle(paste("ARI : ", round(adj.rand.index(Y_train,res),4) ,sep = ""))
  ggsave(paste('Predi_SELF_EXP_ARI_Mu_1e',exp_mu,".png",sep = ""))
  
  
  
  #######
  # Scoring
  setwd("/SCMK - image/MultiKernels/Test")
  for (i in 1:nb_test){
    print(i)
    
    #SCMK_NMI
    res=SCMK(Kernel = Kernels_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_NMI$alpha, beta=param_SCMK_NMI$beta, gamma=param_SCMK_NMI$gamma)
    result_NMI_test[i,1] <- NMI(as.vector(Y_test),as.vector(res$pred))
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe") + 
        ggtitle(paste("NMI : ", round(result_NMI_test[i,1],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_NMI_Mu_1e',exp_mu,".png",sep = ""))
      poids_NMI[,1] = res$w
    }
    
    #SCMK_ARI
    
    res=SCMK(Kernel = Kernels_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_ARI$alpha, beta=param_SCMK_ARI$beta, gamma=param_SCMK_ARI$gamma)
    result_ARI_test[i,1] <-adj.rand.index(Y_test,res$pred)
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("ARI : ", round(result_ARI_test[i,1],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_ARI_Mu_1e',exp_mu,".png",sep = ""))
      poids_ARI[,1] = res$w
    }
    
    #SCMK_KMEANS_NMI
    res=SCMK_KMEANS(Kernel = Kernels_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_NMI$alpha, beta=param_SCMK_KMEANS_NMI$beta)
    result_NMI_test[i,2] <- NMI(as.vector(Y_test),as.vector(res$pred))
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("NMI : ", round(result_NMI_test[i,2],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_KMEANS_MNI_Mu_1e',exp_mu,".png",sep = "")) 
      poids_NMI[,2] = res$w
    }
    
    #SCMK_KMEANS_ARI
    res=SCMK_KMEANS(Kernel = Kernels_test, c=c, nb_etape=nb_etape, mu=mu, alpha=param_SCMK_KMEANS_ARI$alpha, beta=param_SCMK_KMEANS_ARI$beta)
    result_ARI_test[i,2] <-adj.rand.index(Y_test,res$pred)
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res$pred))) +  aes(x=X1,y=X2,col=as.factor(X3)) +
        geom_point() + xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("ARI : ", round(result_ARI_test[i,2],4) ,sep = ""))
      ggsave(paste('Predi_SCMK_KMEANS_ARI_Mu_1e',exp_mu,".png",sep = ""))
      poids_ARI[,2] = res$w
    }
    
    #Self_expressiveness_NMI
    affinity_self = Self_expressiveness(Kernel = Kernels_test, alpha = param_Self$alpha_NMI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
    res = specc_adjacence(affinity_self$Z,c = c)
    result_NMI_test[i,3] <- NMI(as.vector(Y_test),as.vector(res))
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
        xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("NMI : ", round(result_NMI_test[i,3],4) ,sep = ""))
      ggsave(paste('Predi_SELF_EXP_MNI_Mu_1e',exp_mu,".png",sep = ""))
      poids_NMI[,3] = affinity_self$w
    }
    
    #Self_expressiveness_ARI
    affinity_self = Self_expressiveness(Kernel = Kernels_test, alpha = param_Self$alpha_ARI, mu = mu, nb_etape = nb_etape, tol = 1e-3)
    res = specc_adjacence(affinity_self$Z,c = c)
    result_ARI_test[i,3] <-adj.rand.index(Y_test,res)
    
    if(i == nb_test){
      ggplot(data.frame(cbind(X_test,res))) +  aes(x=V1,y=V2,col=as.factor(res)) + geom_point() +
        xlab('1ère coordonnée') + ylab('2ème coordonnée') + labs(colour = "Groupe")+ 
        ggtitle(paste("ARI : ", round(result_ARI_test[i,3],4) ,sep = ""))
      ggsave(paste('Predi_SELF_EXP_ARI_Mu_1e',exp_mu,".png",sep = ""))
      poids_ARI[,3] = affinity_self$w
    }
    
    
  }  
  
  #######
  # Boxplot
  name_file_NMI=paste("Boxplot_NMI_Mu_1e",exp_mu,".png",sep = "")
  df_result_NMI = data.frame(cbind(matrix(result_NMI_test,nrow=3*nb_test),rep(c("SCMK","SCMK_KMEANS","SELF_EXP"),each=nb_test)))
  colnames(df_result_NMI) <- c("NMI","Methode")
  df_result_NMI$NMI <- as.numeric(df_result_NMI$NMI)
  ggplot(df_result_NMI,aes(x=Methode,y=NMI,fill=Methode)) + geom_boxplot() + ylim(0,1)
  ggsave(name_file_NMI)
  
  
  name_file_ARI=paste("Boxplot_ARI_Mu_1e",exp_mu,".png",sep = "")
  df_result_ARI = data.frame(cbind(matrix(result_ARI_test,nrow=3*nb_test),rep(c("SCMK","SCMK_KMEANS","SELF_EXP"),each=nb_test)))
  colnames(df_result_ARI) <- c("ARI","Methode")
  df_result_ARI$ARI <- as.numeric(df_result_ARI$ARI)
  ggplot(df_result_ARI,aes(x=Methode,y=ARI,fill=Methode)) + geom_boxplot() + ylim(0,1) 
  ggsave(name_file_ARI)
  
  
  # graphique poids :
  ## ARI
    tmp = data.frame(cbind(as.vector(sqrt(poids_ARI)), rep(methodes,each=nb_kernels), rep(kernel_names,nb_methode)))
  
  colnames(tmp) <- c("valeur","Methode","Noyau")
  tmp$valeur <- as.numeric(tmp$valeur)
  ggplot(data=tmp, aes(x=Methode, y=valeur,fill=Noyau)) +
    geom_bar(stat="identity") + ylab("Pondération")
  
  ggsave(paste("Ponderation_ARI_Mu_1e",exp_mu,".png",sep = ""))
  
  ## NMI
    tmp = data.frame(cbind(as.vector(sqrt(poids_NMI)), rep(methodes,each=nb_kernels), rep(kernel_names,nb_methode)))
  
  colnames(tmp) <- c("valeur","Methode","Noyau")
  tmp$valeur <- as.numeric(tmp$valeur)
  ggplot(data=tmp, aes(x=Methode, y=valeur,fill=Noyau)) +
    geom_bar(stat="identity") + ylab("Pondération")
  
  ggsave(paste("Ponderation_NMI_Mu_1e",exp_mu,".png",sep = ""))
}
```


```{r}

```

