---
title: "SCMK"
output: html_notebook
---

# Chargement des library
```{r}
rm(list=ls())
```


```{r}
#install.packages("orthoDr")
library(orthoDr) #bug, penser à installer XQuartz
#install.packages("pracma")
library(pracma)
library(quadprog)
```

# SCMK :

```{r}
fun<-function(P,args){
    res = args$beta * Trace(t(P) %*% args$L %*% P) + args$gamma * base::norm(args$F1 - P %*% args$Q,type='F')^2
    return(res)
}
```

```{r}
grad<-function(P,args){
    res = 2*args$beta * args$L %*% P - 2 * args$gamma * args$F1 %*% t(args$Q) 
    return(res)
}
```


```{r}
SCMK <- function(data,c=3,alpha=1,beta=1,gamma=1,mu=1,nb_etape=200,tol=1e-3){
    #data : tensor with dim(n,n,r) where data[:,:,k] is the kernel k on data
    # k : number of cluster 
    
    
    # Initialisation des variables 
    if(length(dim(data))==2){
        r = 1
        n = dim(data)[1]
    }
    else {
        r = dim(data)[3]
        n = dim(data)[1]
    }
    Z = matrix(runif(n*n,0,1),nrow=n,ncol=n)
    P = gramSchmidt( matrix(runif(n*c,0,1),nrow=n,ncol=c))$Q
    Q = gramSchmidt( matrix(runif(c*c,0,1),nrow=c,ncol=c))$Q
    F1 = P %*% Q
    
    list_argmax=max.col(F1)#donne liste indice du max par ligne
    for (i in 1:n){
        F1[i,list_argmax[i]] = 1
        F1[i,-list_argmax[i]] = 0
    }
    F_init=F1
    Y = matrix(0,nrow=n,ncol=n) # hésitation avec : Y=np.zeros((n,1)) vu le code matlab...
    w = matrix(1,nrow=r,ncol=1)/(r^2) ## On veut que sum(sqrt(w))=1
    
    etape=1
    
    
    S = matrix(0,nrow=n,ncol=n)
    h = matrix(1,nrow=r,ncol=1)
    
    while( (etape<nb_etape+1) & (base::norm(Z-S,type='F') > base::norm(Z,type='F')*tol) ){
        #print(etape)
        #''' Calcul de Kw '''
        Kw = matrix(0,nrow=n,ncol=n)
        
        if(r==1) {
            Kw = data
        }
        else {
            for (i in 1:r) Kw = Kw + w[i]*data[,,i]
        }

       #  Update de S 
         S = Z-Y/mu
         S[abs(S)<alpha/mu] = alpha/mu
         S = (abs(S)-alpha/mu) * sign(S)
         S = S-diag(diag(S))
         S[S<0]=0
        
       # Update de Z 
        E = S + Y/mu
        dist_p = (P^2) %*% matrix(1,nrow=c,ncol=n) - 2 * P %*% t(P) + matrix(1,nrow=n,ncol=c) %*% t(P^2) # ||P_i,: - P_j,:||^2
        tmp1 = mu*diag(n) + 2*Kw
        tmp2 = beta/2 * dist_p - 2* Kw - mu * E # voir si c'est E ou t(E) matlab
        Z = solve(tmp1) %*% (-tmp2)
        Z = Z - diag(diag(Z))
        Z[Z<0] = 0
        Z = (Z+t(Z))/2
        
        # Update de Y 
        Y = Y + mu * (S-Z)
        
       #  Update de P 
        D = diag(rowSums(Z))
        L = D - Z
        args=list('L'=L,'F1'=F1,'Q'=Q,'beta'=beta,'gamma'=gamma)
        P = ortho_optim(P,fun,grad=grad,args= args,verbose = FALSE)$B
        
        # Update de Q 
        decomposition = svd(t(F1) %*% P)
        Q = decomposition$u %*% t(decomposition$v)
        
       #  Update de F 
        F1 = P %*% Q
        list_argmax=max.col(F1) #donne liste indice du max par ligne
        for (i in 1:n){
            F1[i,list_argmax[i]] = 1
            F1[i,-list_argmax[i]] = 0
        }
        if(r>1){
            #''' Calcul de h '''
            for (i in 1:r) h[i] = Trace( data[,,i] - 2*data[,,i]%*%Z + t(Z) %*% data[,,i] %*%Z )

            #''' Update de w '''
            for (i in 1 : r) w[i] = (h[i] * sum(1./h))^(-2)
        }
        etape=etape+1
        #print(dist_p)
    }
    #print(Z)
    #print(S)
    output=list("pred"=list_argmax,"Z"=Z,'K'=Kw,'w'=w,'P'=P,'F'=F1,'F_init'=F_init)
    return(output)
}
```

# Essais :

```{r}
# library(tensorr)
# dims <- c(2,2,2)
# z <- array(c(10,0,0,0,20,0,0,0), dims)
# 
# z2 <- array(c(30,0,0,0,40,0,0,0), dims)
```

# Données simulées :

```{r}
X1=matrix(rnorm(200),nrow=100,ncol=2)
X2=matrix(rnorm(200,10),nrow=100,ncol=2)
X=as.matrix(rbind(X1,X2))
plot(X[,1],X[,2])
```

```{r}
RBF<-function(X,sigma=1){
    n=nrow(X)
    res=matrix(0,n,n)
    for(i in 1:n){
        for(j in 1:n){
            res[i,j]=exp(-sum((X[i,]-X[j,])^2)/(2*sigma))
        }
    }
    return(res)
}

polynomial<-function(X,deg=1){
    n=nrow(X)
    res=matrix(0,n,n)
    for(i in 1:n){
        for(j in 1:n){
            res[i,j]=(t(X[i,])%*%X[j,]+1)^deg
        }
    }
    return(res)
}
```

```{r}
data=polynomial(X)
```


```{r}
#trace(ortho_optim,edit=TRUE) permet de modifier la fonction, passer la condition d'orthogonalité à 1e-8.
res=SCMK(data,c=2,nb_etape = 200,mu=10^3,alpha=10^0,beta=10^1,gamma =1e-3)
#print(res)
plot(X[,1],X[,2],col=res$pred)
```
```{r}
res$pred
```


```{r}
Y=rbind(zeros(100,1),ones(100,1))

library(aricode) #NMI
NMI(as.vector(Y),as.vector(res$pred))

library(fossil)
rand.index(Y,res$pred)
adj.rand.index(Y,res$pred)
```

```{r}
#print(abs((res$F_init-res$F)))
```


```{r}
res2=kmeans(X,3)
plot(X[,1],X[,2],col=res2$cluster)
```

# Test des hyper-paramètres :

```{r}
#trace(ortho_optim,edit=TRUE)
```

```{r}
mu=1e3
nb_test =5
list_res_NMI <- c()
list_res_rand <- c()
Mat_res_NMI = zeros(7,7)
Mat_res_rand = zeros(7,7)

tmp_res_NMI = rep(0,nb_test)
tmp_res_rand = rep(0,nb_test)
for (a in -3:3){
    for (b in -3:3){
        for(g in -3:3){
            print(c(a,b,g))
            for(x in 1:nb_test){
                res=SCMK(data,c=2,nb_etape = 50,mu=mu,gamma =10^g,alpha=10^a,beta=10^b)
                tmp_res_NMI[x] = NMI(as.vector(Y),as.vector(res$pred))
                tmp_res_rand[x] =rand.index(Y,res$pred)
            }
            Mat_res_NMI[b+4,g+4] = mean(tmp_res_NMI)
            Mat_res_rand[b+4,g+4] = mean(tmp_res_rand)
        }
    }
    list_res_NMI[[a+4]]=Mat_res_NMI
    list_res_rand[[a+4]]=Mat_res_rand
}
```


```{r}
list_res_NMI
```

```{r}
res=SCMK(data,c=2,nb_etape = 50,mu=10^3,alpha=10^0,beta=10^2,gamma =10^-3)
NMI(as.vector(Y),as.vector(res$pred))
rand.index(Y,res$pred)
#print(res)
plot(X[,1],X[,2],col=res$pred)
```

```{r}
gamma=0
nb_test =5
list_res_NMI <- c()
list_res_rand <- c()
Mat_res_NMI = zeros(7,7)
Mat_res_rand = zeros(7,7)

tmp_res_NMI = rep(0,nb_test)
tmp_res_rand = rep(0,nb_test)
for (a in -3:3){
    for (b in -3:3){
        for(mu in -3:3){
            print(c(a,b,mu))
            for(x in 1:nb_test){
                res=SCMK(data,c=2,nb_etape = 50,mu=10^mu,gamma=gamma,alpha=10^a,beta=10^b)
                tmp_res_NMI[x] = NMI(as.vector(Y),as.vector(res$pred))
                tmp_res_rand[x] =rand.index(Y,res$pred)
            }
            Mat_res_NMI[b+4,mu+4] = mean(tmp_res_NMI)
            Mat_res_rand[b+4,mu+4] = mean(tmp_res_rand)
        }
    }
    list_res_NMI[[a+4]]=Mat_res_NMI
    list_res_rand[[a+4]]=Mat_res_rand
}
```


```{r}
list_res_NMI
```

```{r}
res=SCMK(data,c=2,nb_etape = 50,mu=10^0,alpha=10^1,beta=10^-1,gamma =0)
#print(res)
plot(X[,1],X[,2],col=res$pred)
```

Tester un exemple mélange puis noyaux différentes largeurs de bandes (noyaux gaussiens) pour tester le mélange de noyaux.
Tester d'enlever Q dans le code !! Remplacer par l'argmax de P
Tester juste Z puis faire le spectral clustering.


# Self-expressiveness


```{r}
Self_expressiveness <- function(data,alpha=1,mu=1,nb_etape=200,tol=1e-3){
    #data : tensor with dim(n,n,r) where data[:,:,k] is the kernel k on data
    
    
    # Initialisation des variables 
    if(length(dim(data))==2){
        r = 1
        n = dim(data)[1]
    }
    else {
        r = dim(data)[3]
        n = dim(data)[1]
    }
    Z = matrix(runif(n*n,0,1),nrow=n,ncol=n)
    
    Y = matrix(0,nrow=n,ncol=n)
    w = matrix(1,nrow=r,ncol=1)/(r^2) ## On veut que sum(sqrt(w))=1
    
    etape=1
    
    
    S = matrix(0,nrow=n,ncol=n)
    h = matrix(1,nrow=r,ncol=1)
    
    while( (etape<nb_etape+1) & (base::norm(Z-S,type='F') > base::norm(Z,type='F')*tol) ){
        #print(etape)
        #''' Calcul de Kw '''
        Kw = matrix(0,nrow=n,ncol=n)
        
        if(r==1) {
            Kw = data
        }
        else {
            for (i in 1:r) Kw = Kw + w[i]*data[,,i]
        }

       #  Update de S 
         S = Z-Y/mu
         S[abs(S)<alpha/mu] = alpha/mu
         S = (abs(S)-alpha/mu) * sign(S)
         S = S-diag(diag(S))
         S[S<0]=0
        
       # Update de Z 
        E = S + Y/mu
        tmp1 = mu*diag(n) + 2*Kw
        tmp2 = - 2* Kw - mu * E
        Z = solve(tmp1) %*% (-tmp2)
        
        Z = Z - diag(diag(Z))
        Z[Z<0] = 0
        Z = (Z+t(Z))/2
        
        # Update de Y 
        Y = Y + mu * (S-Z)
        
        if(r>1){
            #''' Calcul de h '''
            for (i in 1:r) h[i] = Trace( data[,,i] - 2*data[,,i]%*%Z + t(Z) %*% data[,,i] %*%Z )

            #''' Update de w '''
            for (i in 1 : r) w[i] = (h[i] * sum(1./h))^(-2)
        }
        etape=etape+1
        #print(dist_p)
    }
    #print(Z)
    #print(S)
    output=list("Z"=Z,'K'=Kw,'w'=w)
    return(output)
}
```


```{r}
X1=matrix(rnorm(200),nrow=100,ncol=2)
X2=matrix(rnorm(200,10),nrow=100,ncol=2)
X3=matrix(rnorm(200,20),nrow=100,ncol=2)
X=as.matrix(rbind(X1,X2,X3))
plot(X[,1],X[,2])
```


```{r}
data=polynomial(X,2)
image(x=1:300,y=1:300,z=data)
```


```{r}
res = Self_expressiveness(data = data,alpha = 10^5,mu=10^-3,nb_etape = 50,tol = 1e-3)
affinity = res$Z
image(x=1:300,y=1:300,z=res$Z)
```


```{r}
library(kernlab)
res=specc(x=data,centers=3)
plot(X[,1],X[,2],col=res)
```

```{r}
L = diag(rowSums(affinity)) - affinity
decomposition = svd(L)
U=decomposition$u[,298:300]
for (i in 1:nrow(U))
{
    U[i,]=U[i,]/sqrt(sum(U[i,]^2))
}
plot(U[,1],U[,2])
plot(U[,1],U[,3])
plot(U[,2],U[,3])

res=kmeans(U,3)
plot(X[,1],X[,2],col=res$cluster)
```


```{r}
SCMK_modif <- function(data,c=3,alpha=1,beta=1,mu=1,nb_etape=200,tol=1e-3){
    #data : tensor with dim(n,n,r) where data[:,:,k] is the kernel k on data
    # c : number of cluster 
    
    
    # Initialisation des variables 
    if(length(dim(data))==2){
        r = 1
        n = dim(data)[1]
    }
    else {
        r = dim(data)[3]
        n = dim(data)[1]
    }
    Z = matrix(runif(n*n,0,1),nrow=n,ncol=n)
    P = gramSchmidt( matrix(runif(n*c,0,1),nrow=n,ncol=c))$Q
    
    F1 = zeros(n,c)
    res=kmeans(P,c)$cluster
    for (i in 1:n){
        F1[i,res[i]] = 1
    }
    
    Y = matrix(0,nrow=n,ncol=n)
    w = matrix(1,nrow=r,ncol=1)/(r^2) ## On veut que sum(sqrt(w))=1
    
    etape=1
    
    
    S = matrix(0,nrow=n,ncol=n)
    h = matrix(1,nrow=r,ncol=1)
    
    while( (etape<nb_etape+1) & (base::norm(Z-S,type='F') > base::norm(Z,type='F')*tol) ){
        #print(etape)
        #''' Calcul de Kw '''
        Kw = matrix(0,nrow=n,ncol=n)
        
        if(r==1) {
            Kw = data
        }
        else {
            for (i in 1:r) Kw = Kw + w[i]*data[,,i]
        }

       #  Update de S 
         S = Z-Y/mu
         S[abs(S)<alpha/mu] = alpha/mu
         S = (abs(S)-alpha/mu) * sign(S)
         S = S-diag(diag(S))
         S[S<0]=0
        
       # Update de Z 
        E = S + Y/mu
        dist_p = (P^2) %*% matrix(1,nrow=c,ncol=n) - 2 * P %*% t(P) + matrix(1,nrow=n,ncol=c) %*% t(P^2) # ||P_i,: - P_j,:||^2
        tmp1 = mu*diag(n) + 2*Kw
        tmp2 = beta/2 * dist_p - 2* Kw - mu * E # voir si c'est E ou t(E) matlab
        Z = solve(tmp1) %*% (-tmp2)
        Z = Z - diag(diag(Z))
        Z[Z<0] = 0
        Z = (Z+t(Z))/2
        
        # Update de Y 
        Y = Y + mu * (S-Z)
        
       #  Update de P 
        D = diag(rowSums(Z))
        L = D - Z
        P = svd(L)
        P = P$u[,(n-c+1):n]
        for (i in 1:nrow(U))
        {
            P[i,]=P[i,]/sqrt(sum(P[i,]^2))
        }
       #  Update de F 
        res=kmeans(P,c,nstart = 30)$cluster
        for (i in 1:n){
            F1[i,res[i]] = 1
            F1[i,-res[i]] = 0
        }
        if(r>1){
            #''' Calcul de h '''
            for (i in 1:r) h[i] = Trace( data[,,i] - 2*data[,,i]%*%Z + t(Z) %*% data[,,i] %*%Z )

            #''' Update de w '''
            for (i in 1 : r) w[i] = (h[i] * sum(1./h))^(-2)
        }
        etape=etape+1
        #print(dist_p)
    }
    #print(Z)
    #print(S)
    output=list("pred"=res,"Z"=Z,'K'=Kw,'w'=w,'P'=P,'F'=F1)
    return(output)
}
```


```{r}
res=SCMK_modif(data,c=3,nb_etape =200,mu=10^-1,alpha=10^1,beta=10^-1)
#print(res)
plot(X[,1],X[,2],col=res$pred)
```



```{r}
data=iris
data=data[,-5]
data=data.matrix(data)
data=polynomial(data,2)
image(x=1:150,y=1:150,z=data)
```

```{r}
res = Self_expressiveness(data = data,alpha = 1e2,mu=10^-3,nb_etape = 50,tol = 1e-3)
affinity = res$Z
image(x=1:150,y=1:150,z=res$Z)
```

```{r}
D = diag(rowSums(affinity))
L = D - affinity
decomposition = svd(L)
U=decomposition$u[,148:150]
for (i in 1:nrow(U))
{
    U[i,]=U[i,]/sqrt(sum(U[i,]^2))
}
plot(U[,1],U[,2])
plot(U[,1],U[,3])
plot(U[,2],U[,3])

res=kmeans(U,3)
plot(iris$Petal.Width,iris$Sepal.Width,col=res$cluster)
```


